package hr.element.pe {

trait Solveable{
  val NUMBER: Int
  def solve(): String
}

import scala.collection.mutable.HashMap

object Problems extends HashMap[Int,Solveable]

import hr.element.pe.problems._

object RunProblem{
  def main( args: Array[String] ) {
    println( Problem0044.solve() )
  }
}

}
package hr.element.pe.problems {

import scala.annotation.tailrec
import hr.element.pe.Solveable

import scala.collection.immutable.ListSet
import scala.collection.mutable.HashMap

/**
  Pentagonal numbers are generated by the formula, P(n)=n*(3*n-1)/2. The first
    ten pentagonal numbers are:

  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

  It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their
    difference, 70  22 = 48, is not pentagonal.

  Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
    difference is pentagonal and D = |Pk  Pj| is minimised; what is the value
    of D?
*/
object Problem0044 extends Solveable{
  val NUMBER = 44

  def solve() = {

    val res = "?"
    String.valueOf( res )
  }
}

}
